name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  notify-packagist:
    name: 📦 Notify Packagist
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist Update Webhook
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -s -XPOST \
            -H'Content-Type:application/json' \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" \
            -d'{"repository":{"url":"https://github.com/tuxnoob/smallpict-php"}}'
